[package]
name = "ModTestNmap"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = "0.37.1"
plotters = "0.3.7"
xml2json-rs = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.133"
